export const list = [
  {
    id: "1",
    categories: "வேகம்",
    name: "vekam_1",
    title: "ஆக்கம் வேண்டுமெனில்",
    author: "கவிமணி தேசிக விநாயகம் பிள்ளை",
    image: require("../assets/kavithai1.png"),

    audio: require("../assets/audio/aakkam_vaendum_enil.mp3"),
    lyrics: [
      { time: 0.55, text: "ஆக்கம் வேண்டுமெனில்", color: "white" },
      { time: 2.7, text: "-நன்மை அடைய வேண்டுமெனில்", color: "white" },
      { time: 5, text: "ஊக்கம் வேண்டுமப்பா", color: "white" },
      { time: 7.5, text: " - ஓயாது உழைக்க வேண்டுமப்பா", color: "white" },
      { time: 10.8, text: "உண்ணும் உணவுக்கும்", color: "white" },
      { time: 12.5, text: "- இடுப்பில் உடுக்கும் ஆடைக்கும்", color: "white" },
      { time: 15.8, text: "மண்ணில் அந்நியரை", color: "white" },
      { time: 18, text: "நம்பி வாழ்தல் வாழ்வாமோ?", color: "white" },
      { time: 21, text: "உண்ணும் உணவுக் கேங்காமல்", color: "white" },
      { time: 23.3, text: "உடுக்கும் ஆடையைக் களையாமல்", color: "white" },
      { time: 26.5, text: "பண்ணும் தொழில்கள்", color: "white" },
      { time: 28, text: "பல காண்போம்", color: "white" },
      { time: 30, text: "பஞ்சப் பேயைத்", color: "white" },
      { time: 31, text: "துரத்திடுவோம்", color: "white" },
      { time: 33.5, text: "அண்ணல் காந்திவழி பற்றி", color: "white" },
      { time: 36.5, text: "அகிலம் புகழ வாழ்ந்திடுவோம்", color: "white" },
      { time: 39, text: "அகிலம் புகழ வாழ்ந்திடுவோம்", color: "white" },
    ],
  },
  {
    id: "2",
    categories: "வேகம்",
    name: "vekam_2",
    title: "பண்பாடு காண்போம்",
    author: "சு. குணசேகரன்",
    image: require("../assets/kavithai2.png"),
    audio: require("../assets/audio/panpaadu_kaappom.m4a"),
    lyrics: [
      { time: 0.1, text: "தமிழும் கலையும்", color: "white" },
      { time: 1.9, text: "இணைந்தே வந்ததை", color: "white" },
      { time: 3.6, text: "தம்மானத் தமிழர் ", color: "white" },
      { time: 5.1, text: "வரலாறு செப்பிடும்", color: "white" },
      { time: 7.2, text: "புவியில் நம்மினம் உயர்வு கண்டதை", color: "white" },
      { time: 10.1, text: "கவிஞர் பலரும்", color: "white" },
      { time: 11.4, text: "பாட்டினில் கூறினர்", color: "white" },
      { time: 13.5, text: "தமிழன் புகழை", color: "white" },
      { time: 15.2, text: "இமயத்தில் ஏற்றிய", color: "white" },
      { time: 17.4, text: "தகைமைச் சிங்கத் தமிழன் வழியில்", color: "white" },
      { time: 20.2, text: "தரணி யெங்கும்", color: "white" },
      { time: 21.9, text: " நம்தமிழ் நெறியைத்", color: "white" },
      { time: 23.5, text: "திறம் சாற்றிப்", color: "white" },
      { time: 25, text: " புகழ் சேர்போம்!", color: "white" },
      { time: 27.3, text: " உழைப்பு", color: "white" },
      { time: 28.5, text: " உண்மை கோட்பா டென்றே ", color: "white" },
      { time: 30.8, text: " உதிக்க வைத்து ", color: "white" },
      { time: 32.2, text: " இளையர் மனத்தை ", color: "white" },
      {
        time: 34,
        text: " உரம் சேர்த்த மண்ணில் வளர்ப்போம்,",
        color: "white",
      },
      { time: 36.6, text: " உறுதியாய் நின்று ", color: "white" },
      { time: 38.2, text: "  உண்மை உரைப்போம் ", color: "white" },
      { time: 40.5, text: " வழிவழி வந்திட்ட  ", color: "white" },
      { time: 42.2, text: " பண்டாட்டைக் காத்து ", color: "white" },
      { time: 44.3, text: " வெறிமுறை விரட்டி ", color: "white" },
      { time: 46, text: "  நீதியை நாட்டிடு ", color: "white" },
      { time: 48, text: " தனியினம் ", color: "white" },
      { time: 49.1, text: " ஒன்றுண் டென்பது ", color: "white" },
      { time: 50.3, text: " உண்மையெனில்", color: "white" },
      { time: 51.5, text: " தமிழினம் ஒன்றேதான் ", color: "white" },
      { time: 53.6, text: " இப்புவியில் காட்டிடு! ", color: "white" },
    ],
  },
  {
    id: "3",
    categories: "தொனி",
    name: "thoni_1",
    title: "அழகின் சிரிப்பு",
    author: "பாவேந்தர் பாரதிதாசன்",
    image: require("../assets/kavithai3.png"),
    audio: require("../assets/audio/thoni_1.m4a"),
    lyrics: [
      {
        time: 1.2,
        text: "காலையிளம் பரிதியிலே அவளைக் கண்டேன்!",
        color: "red",
        direction: "down",
      },
      {
        time: 4.5,
        text: "கடற்பரப்பில், ஒளிப்புனலில் கண்டேன்! ",
        color: "red",
        direction: "down",
      },
      {
        time: 7.5,
        text: "அந்தச் சோலையிலே, மலர்களிலே, தளிர்கள் தம்மில்,",
        color: "green",
        direction: "up",
      },
      {
        time: 13.4,
        text: "தொட்ட இடம் எலாம் கண்ணில் தட்டுப்பட்டாள்!",
        color: "red",
        direction: "down",
      },
      {
        time: 17,
        text: "மாலையிலே மேற்றிசையில் இலகு கின்ற",
        color: "red",
        direction: "down",
      },
      {
        time: 21.8,
        text: "மாணிக்கச் சுடரிலவள் இருந்தாள் ",
        color: "green",
        direction: "up",
      },
      {
        time: 26,
        text: "ஆலஞ் சோலையிலே கிளைதோறும் கிளியின் கூட்டந் தனில்",
        color: "red",
        direction: "down",
      },
      {
        time: 31,
        text: "அந்த 'அழகெ'ன்பாள் கவிதை தந்தாள்.",
        color: "green",
        direction: "up",
      },
      {
        time: 35.8,
        text: "சிறு குழந்தை விழியினிலே ஒளியாய் நின்றாள்;",
        color: "red",
        direction: "down",
      },
      {
        time: 39.5,
        text: "திருவிளக்கிற் சிரிக்கின்றாள்,",
        color: "red",
        direction: "down",
      },
      {
        time: 42.5,
        text: "நாரெடுத்து நறுமலரைத் ",
        color: "green",
        direction: "up",
      },
      {
        time: 45,
        text: " தொடுப்பாளின் விரல்வளைவில்",
        color: "green",
        direction: "up",
      },
      {
        time: 48,
        text: "நாடகத்தைச் செய்கின்றாள்;",
        color: "red",
        direction: "down",
      },
      {
        time: 50.5,
        text: "அடடே செந்தோட் புறத்தினிலே கலப்பையுடன் உழவன் செல்லும்",
        color: "green",
        direction: "up",
      },
      {
        time: 57,
        text: "புதுநடையில் பூரித்தாள்;",
        color: "green",
        direction: "up",
      },
      {
        time: 59.5,
        text: "விளைந்த நன்செய் நிறத்தினிலே",
        color: "red",
        direction: "down",
      },
      {
        time: 62,
        text: "என் விழியை நிறுத்தினாள்;",
        color: "green",
        direction: "up",
      },
      {
        time: 64.5,
        text: "என் நெஞ்சத்தில் குடியேறி மகிழ்ச்சி செய்தாள்.",
        color: "red",
        direction: "down",
      },
      {
        time: 69.5,
        text: "திசைகண்டேன், வான்கண்டேன், உட்புறத்துச் செறிந்தனவாம்",
        color: "green",
        direction: "up",
      },
      {
        time: 74.5,
        text: "பலப்பலவும் கண்டேன். ",
        color: "red",
        direction: "down",
      },
      {
        time: 77.5,
        text: "யாண்டும் அசைவனவும் நின்றனவும் கண்டேன்.",
        color: "green",
        direction: "up",
      },
      { time: 82, text: "மற்றும்", color: "red", direction: "down" },
      {
        time: 83.5,
        text: "அழகுதனைக் கண்டேன் ",
        color: "green",
        direction: "up",
      },
      {
        time: 85.5,
        text: "நல்லின்பங் கண்டேன்.பசையுள்ள பொருளிலெலாம் பசையவன் காண்!",
        color: "red",
        direction: "down",
      },
      {
        time: 93,
        text: "பழமையினால் சாகாத இளையவள் காண்!",
        color: "green",
        direction: "up",
      },
      {
        time: 97.5,
        text: "நசையோடு நோக்கடா எங்கும் உள்ளான்!",
        color: "red",
        direction: "down",
      },
      {
        time: 100.5,
        text: "நல்லழகு வசப்பட்டால் துன்ப மில்லை.",
        color: "green",
        direction: "up",
      },
    ],
  },
  {
    id: "4",
    categories: "தொனி",
    name: "thoni_2",
    title: "தைத்தாய்க்கு வணக்கம்",
    author: "மீ.மணிகண்டன்",
    image: require("../assets/kavithai4.png"),
    audio: require("../assets/audio/thoni_variant.mp3"),
    lyrics: [
      {
        time: 3,
        text: "பழையதனைப் பறைசாற்றிப் ",
        color: "red",
        direction: "down",
      },
      {
        time: 6.2,
        text: "பருதியொளி யாய்நீண்டு ",
        color: "green",
        direction: "up",
      },
      {
        time: 9,
        text: "விழுதுகளாய் வேரூன்றி ",
        color: "red",
        direction: "down",
      },
      {
        time: 12,
        text: "வினையழிக்கும் சூழ்கொண்டு.",
        color: "green",
        direction: "up",
      },
      {
        time: 15,
        text: "குழுவினராய் ஒன்றாகி, குலங்காக்கும் கற்கண்டு",
        color: "red",
        direction: "down",
      },
      {
        time: 19,
        text: "உழவர்களைக் காப்பாற்றும் உறுதிதனை உட்கொள்வோம்!",
        color: "green",
        direction: "up",
      },
      {
        time: 25,
        text: "எழுதாத கவிதைகளாய்",
        color: "red",
        direction: "down",
      },
      {
        time: 27,
        text: "ஏருழுது நிலம்காக்க",
        color: "green",
        direction: "up",
      },
      {
        time: 29,
        text: "பொழுதெல்லாம் கண்விழிக்கும் ",
        color: "red",
        direction: "down",
      },
      {
        time: 32,
        text: "உண்ணியரின் உயிர்காக்க,",
        color: "green",
        direction: "up",
      },
      {
        time: 34,
        text: "புழதிக்கால் கைகளுக்குப் பொன்னாலே அலங்கரிக்க,",
        color: "red",
        direction: "down",
      },
      {
        time: 39,
        text: "பழுதற்ற மனத்தாலே பகிர்ந்திடுவோம் உறுதிமொழி!",
        color: "green",
        direction: "up",
      },
      {
        time: 44,
        text: "அழுகின்ற அவர்கண்கள்",
        color: "green",
        direction: "up",
      },
      {
        time: 46.5,
        text: "ஆனந்தம் பார்த்திடவே",
        color: "red",
        direction: "down",
      },
      {
        time: 49,
        text: "விழுகின்ற வியர்வையிலே",
        color: "green",
        direction: "up",
      },
      {
        time: 51,
        text: "வைரங்கள் முளைத்திடவே",
        color: "red",
        direction: "down",
      },
      {
        time: 53.3,
        text: "உழுதுண்டு வாழ்வதுவே",
        color: "red",
        direction: "down",
      },
      {
        time: 55.6,
        text: "உயர்வென்று காட்டிடவே",
        color: "green",
        direction: "up",
      },
      {
        time: 58,
        text: "எழுதிட்டோம் இனியென்ன  ",
        color: "red",
        direction: "down",
      },
      {
        time: 60,
        text: "என்றென்றும் நற்பொழுதே!",
        color: "green",
        direction: "up",
      },
      {
        time: 62.5,
        text: "மழையென்றும் வரந்தரவே ",
        color: "red",
        direction: "down",
      },
      {
        time: 65,
        text: "மரந்தொட்டு வணங்குகிறேன்! ",
        color: "green",
        direction: "up",
      },
      {
        time: 67,
        text: "கழனியிலே பெரியோரின்",
        color: "red",
        direction: "down",
      },
      {
        time: 69,
        text: "கால்தொட்டு வணங்குகிறேன்!",
        color: "green",
        direction: "up",
      },
      {
        time: 72,
        text: "ஒழுக்கத்தின் ஒளிப்பிழம்பாம்",
        color: "red",
        direction: "down",
      },
      {
        time: 74,
        text: "ஓர் ஆன்மா வணங்குகிறேன்!",
        color: "green",
        direction: "up",
      },
      {
        time: 76.6,
        text: "தழலொற்று வாழ்வேற்ற ",
        color: "red",
        direction: "down",
      },
      {
        time: 80,
        text: "தைத்தாயை வணங்குகிறேன்!",
        color: "green",
        direction: "up",
      },
    ],
  },
  {
    id: "5",
    categories: "உச்சரிப்பு",
    name: "uccarippu_1",
    title: "விருட்சங்கள்",
    author: "கவிஞர் வாலி",
    image: require("../assets/kavithai5.png"),
    audio: require("../assets/audio/virutchangal.m4a"),
    lyrics: [
      { time: 0.7, text: "கா<blue>ற்று</blue>ப்" },
      { time: 2, text: "பிச்சைக்கா<blue>ர</blue><green>ன்</green>" },
      { time: 3, text: "காதைக்" },
      { time: 4, text: "கி<red>ள்ளு</red>ம்" },
      { time: 5, text: "போதெ<red>ல்லா</red>ம்..." },
      { time: 6, text: "த<red>லை</red>யாட்டிக்" },
      { time: 7, text: "கொ<green>ண்</green>டி<blue>ரு</blue>க்கும்" },
      {
        time: 8,
        text: "பெ<blue>ரு</blue>மா<red>ள்</red> மாடுக<red>ள்</red>",
      },
      { time: 10, text: "ம<green>ண்ண</green><blue>ர</blue>சி…" },
      { time: 12, text: "மடக்காம<red>லே</red>யே" },
      { time: 13, text: "பிடித்துக்" },
      { time: 14, text: "கொ<green>ண்</green>டி<blue>ரு</blue>க்கும்" },
      { time: 15, text: "பச்சை<red>க்</red> " },
      { time: 16, text: "குடைக<red>ள்</red>…" },
      { time: 17, text: "ப<blue>ற</blue>வைக<red>ளி</red><green>ன்</green>" },
      { time: 18.7, text: "பி<blue>ர</blue>சவ " },
      { time: 19.7, text: "ஆஸ்பத்தி<blue>ரி</blue>க<red>ள்</red>…" },
      { time: 21, text: "கல்<red>லா</red>ல்" },
      { time: 22, text: "அடிபட்டும்" },
      { time: 23, text: "கடிக்க வ<blue>ரா</blue>த" },
      { time: 24.7, text: "<green>நா</green>ய்க<red>ள்</red>…" },
      { time: 26, text: "அக்கி<green>னி</green>ப்" },
      { time: 27, text: "பி<blue>ர</blue>வேசம்" },
      { time: 28, text: "செய்கி<green>ன்</green><blue>ற</blue>…" },
      { time: 29, text: "பத்தி<green>னி</green>" },
      { time: 30, text: "வி<blue>ற</blue>குக<red>ளி</red><green>ன்</green>" },
      {
        time: 31.6,
        text: "பி<blue>ற</blue><green>ந்</green>தகங்க<red>ள்</red>",
      },
      { time: 33, text: "நி<red>ழல்</red>" },
      { time: 34, text: "<green>நா</green>டகத்தை" },
      { time: 35, text: "எ<red>ழு</red>தி…" },
      {
        time: 36.5,
        text: "வ<red>ழி</red>ப் போக்க<blue>ர்</blue>க<red>ளி</red>டம்",
      },
      { time: 38.4, text: "வாசித்துக்" },
      { time: 39, text: "காட்டுகி<green>ன்</green><blue>ற</blue>" },
      {
        time: 40.7,
        text: "வச<green>ன</green> க<blue>ர்</blue>த்தாக்க<red>ள்</red>…",
      },
      { time: 42.5, text: "புய<red>ல்</red>" },
      { time: 43, text: "மே<green>ன</green>கையைப்" },
      { time: 44, text: "பா<blue>ர்</blue>த்தவுட<green>ன்</green>…" },
      { time: 46, text: "<green>நி</green>ஷ்டை" },
      { time: 47, text: "க<red>லை</red><green>ந்</green>து" },
      { time: 47.9, text: "<green>நெ</green>டுங்சா<green>ண்</green> கிடையாக" },
      { time: 50, text: "அவ<red>ள்</red>" },
      { time: 51, text: "கா<red>ல</red>டியி<red>ல்</red>" },
      { time: 52, text: "வி<red>ழு</red><green>ந்</green>து விடும்" },
      { time: 53, text: "விஸ்வாமித்தி<blue>ரர்</blue>க<red>ள்</red> …" },
      { time: 55, text: "ஒவ்வொ<blue>ரு</blue>" },
      { time: 56, text: "வ<blue>ரு</blue>டமும்…" },
      { time: 57, text: "இய<blue>ற்</blue>கை தேவதையி<green>ன்</green>" },
      { time: 59, text: " நே<blue>ர்</blue>த்திக் கட<green>னை</green>த்" },
      { time: 60, text: "தீ<blue>ர்</blue>க்க வே<green>ண்</green>டி…" },
      { time: 62, text: "இ<red>லை</red>யுதி<blue>ர்</blue>" },
      { time: 63, text: "கா<red>ல</red>த்தி<red>ல்</red>" },
      { time: 64, text: "மொட்டை" },
      { time: 65, text: "போட்டுக் கொ<red>ள்ளு</red>ம்" },
      { time: 66, text: "பக்த<blue>ர்</blue>க<red>ள்</red>" },
    ],
  },
  {
    id: "6",
    categories: "உச்சரிப்பு",
    name: "Uccarippu_2",
    title: "சுனாமி ",

    author: "கவிஞர் வைரமுத்து",
    image: require("../assets/kavithai6.jpg"),
    audio: require("../assets/audio/uchcharippu_1.mp3"),
    lyrics: [
      { time: 0.7, text: "ஏ கட<red>லே</red>!" },
      {
        time: 1.3,
        text: "உன் க<blue>ரை</blue>யி<red>ல்</red> இது<blue>வரை</blue>யி<red>ல்</red>",
      },
      {
        time: 3.2,
        text: "கி<red>ளி</red>ஞ்ச<red>ல்</red>க<red>ள்</red>தா<green>னே</green> சேக<blue>ரி</blue>த்தோம்",
      },
      {
        time: 6,
        text: "முத<green>ன்</green> முத<red>லா</red>ய் பி<green>ண</green>ங்க<red>ளை</red>ப்",
      },
      { time: 8, text: "பொ<blue>று</blue>க்குகி<blue>றோ</blue>ம்" },

      { time: 9.5, text: "ஏ கட<red>லே</red>!" },
      {
        time: 10,
        text: "உன் க<blue>ரை</blue>யி<red>ல்</red> இது<blue>வரை</blue>யி<red>ல்</red>",
      },
      {
        time: 13,
        text: "கி<red>ளி</red>ஞ்ச<red>ல்</red>க<red>ள்</red>தா<green>னே</green> சேக<blue>ரி</blue>த்தோம்",
      },
      {
        time: 15,
        text: "முத<green>ன்</green> முத<red>லா</red>ய் பி<green>ண</green>ங்க<red>ளை</red>ப்",
      },
      { time: 17.5, text: "பொ<blue>று</blue>க்குகி<blue>றோ</blue>ம்" },

      { time: 19, text: "ஏ கட<red>லே</red>!" },
      {
        time: 20,
        text: "நீ முத்துக்க<red>ளி</red><green>ன்</green> ப<red>ள்ள</red>த்தாக்கா",
      },
      { time: 22.3, text: "முது மக்க<red>ள்</red> தா<red>ழி</red>யா" },
      {
        time: 24.4,
        text: "உ<green>ன்</green> அ<red>லை</red> எத்த<green>னை</green> விதவைக<red>ளி</red><green>ன்</green>",
      },
      { time: 27.3, text: "வெ<red>ள்ளை</red>ச் சே<red>லை</red>?" },

      {
        time: 29.3,
        text: "உ<green>ன்</green> மீ<green>ன்</green>க<red>ளை</red> நாங்க<red>ள்</red> கூ<blue>று</blue>கட்டியத<blue>ற்</blue>காக",
      },
      {
        time: 33.7,
        text: "எங்க<red>ள்</red> பி<green>ண</green>ங்க<red>ளை</red> நீ  உ<blue>று</blue>கட்டுகி<blue>றா</blue>ய்?",
      },
      {
        time: 36.3,
        text: "உ<green>ன்</green> மீ<green>ன்</green>க<red>ளை</red> நாங்க<red>ள்</red> கூ<blue>று</blue>கட்டியத<blue>ற்</blue>காக",
      },
      {
        time: 39.3,
        text: "எங்க<red>ள்</red> பி<green>ண</green>ங்க<red>ளை </red> நீ உ<blue>று</blue>கட்டுகி<blue>றா</blue>ய்?",
      },
      {
        time: 42,
        text: "அடக்கம் செய்ய ஆ<red>ளி</red><blue>ரா</blue>தெ<green>ன்</green><blue>றா</blue>",
      },
      {
        time: 45.3,
        text: "புதை ம<green>ண</green><red>லு</red>க்கு<red>ள்</red>",
      },
      { time: 46.3, text: "புதைத்து விட்டே போய்விட்டாய்?" },

      {
        time: 48.3,
        text: "பி<green>ண</green>ங்க<red>ளை</red> அடையா<red>ள</red> காட்ட",
      },
      {
        time: 51.3,
        text: "பெ<blue>ற்ற</blue>வ<red>ளை</red>த் தேடி<green>னோ</green>ம்",
      },
      {
        time: 53.3,
        text: "அவ<red>ள்</red> பி<green>ண</green>த்தையே கா<green>ணோ</green>ம்",
      },

      {
        time: 55.3,
        text: "ம<blue>ர</blue><green>ண</green>த்தி<green>ன்</green> மீதே ம<blue>ரி</blue>யாதை போய்விட்டது",
      },

      {
        time: 59.3,
        text: "ப<blue>ற</blue>வைக<red>ள்</red> மொத்தமாய் வந்தா<red>ல்</red> அ<red>ழ</red>கு",
      },

      {
        time: 63.3,
        text: "ம<blue>ர</blue><green>ண</green>ம் தனியே வந்தா<red>ல்</red> அ<red>ழ</red>கு",
      },

      {
        time: 66.3,
        text: "மொத்தமாய் வ<blue>ரு</blue>ம் ம<blue>ர</blue><green>ண</green>த்தி<green>ன்</green> மீது",
      },
      { time: 69, text: "சுத்தமாய் ம<blue>ரி</blue>யாதை இ<red>ல்லை</red>" },
      {
        time: 72.3,
        text: "மொத்தமாய் வ<blue>ரு</blue>ம் ம<blue>ர</blue><green>ண</green>த்தி<green>ன்</green> மீது",
      },
      { time: 74, text: "சுத்தமாய் ம<blue>ரி</blue>யாதை இ<red>ல்லை</red>" },

      {
        time: 77,
        text: "இய<blue>ற்</blue>கையி<green>ன்</green> சவா<red>லில்</red> அ<red>ழி</red>வு<green>ண்</green>டா<red>ல்</red>",
      },
      { time: 80, text: "வி<red>ல</red>ங்கு" },
      {
        time: 81.3,
        text: " இய<blue>ற்</blue>கையி<green>ன்</green> சவா<red>லை</red> எதி<blue>ர்</blue>கொ<green>ண்</green>டா<red>ல்</red>   ",
      },
      {
        time: 82.3,
        text: " ம<green>னி</green>த<green>ன்</green>  ",
      },
    ],
  },
  {
    id: "7",
    categories: "நயம்",
    name: "nayam_1",
    title: "பொங்குவோம் பொங்கல் ",
    author: "கவிஞர் இராஜ்குமார்",
    image: require("../assets/kavithai77.png"),
    lyrics: [
      { time: 6, text: "இளைத்த உழவர் கூட்டம்" },
      { time: 7.5, text: "இன்பம் எனும் ஏற்றல் காண" },
      { time: 10, text: "இருபத்தியோராம் நூற்றாண்டின்" },
      { time: 13, text: "இனிய பொங்கலன்று" },
      { time: 15.5, text: "இரு கரம் கூப்புவோம்." },
      { time: 17, text: "இயற்கையை வேண்டுவோம்" },
      { time: 20, text: "இந்நாளில் சமுதாயச் சண்டை ஒழித்து" },
      { time: 23, text: "சமத்துவ பொங்கல் பொங்க" },
      { time: 26, text: "மூடத்தனம் அழித்து" },
      { time: 27.8, text: "முற்போக்குப் பொங்கல் பொங்க" },
      { time: 29.6, text: "உலகுக்கு உணவை அளிக்கும்" },
      { time: 33, text: "உழவர்களின் உள்ளம் பொங்க" },
      { time: 35.3, text: "உலகத் தமிழர் வாழ்வில்" },
      { time: 37, text: "இன்னல் தீர்ந்த பொங்கல் பொங்க" },
      { time: 39.8, text: "இரும்பென தாக்கியவரையும் துரும்பென" },
      { time: 43, text: "தடுக்கும் தூய தமிழ் வீரம் பொங்க" },
      { time: 46.8, text: "குரும்பாய்க் குட்டுபவரையும்" },
      { time: 49, text: "கரும்பாய்க் காத்து மகிழும்" },
      { time: 51, text: "நம்மவர் நலம் பொங்க" },
      { time: 54, text: "உலகத் தமிழரிடையே" },
      { time: 55, text: "ஒற்றுமை பொங்கல் பொங்க" },

      { time: 57, text: "தமிழ் மணம் எங்கும் பொங்க" },
      { time: 58, text: "தமிழ் மண்ணின் தரம் பொங்க" },
      { time: 61, text: "தமிழர்களே பொங்குவோம் பொங்கல்" },
    ],
    videoPath: require("../assets/video/song4.mp4"),
  },
  {
    id: "8",
    categories: "நயம்",
    title: "இயற்கை",
    name: "nayam_2",
    author: "கவிப்புயல் இனியவன்",
    image: require("../assets/kavithai8.jpg"),
    lyrics: [
      { time: 4.5, text: "சடைத்து நிற்கும் மரத்தை" },
      { time: 7.5, text: "சற்றே கொஞ்சம் உன்னிப்பாய்" },
      { time: 9, text: "பார்த்தேன்." },
      { time: 10, text: "இலைகளின்" },
      { time: 11, text: "அசைவில் சிரிப்பொலி" },
      { time: 13, text: "உதிர்ந்து" },
      { time: 14, text: "விழும் இலையின்" },
      { time: 16, text: "தியாகம்!" },
      { time: 17, text: "துளிர்க்கும் இலையின்" },
      { time: 18, text: "துடிப்பு!" },
      { time: 19, text: "மற்றைய இலையோடு" },
      { time: 22, text: "உரசும் காதல்!" },
      { time: 24, text: "இரசித்துக் கொண்டே" },
      { time: 25, text: "இருக்கலாம்" },
      { time: 26, text: "குடைபோல் நிழல் கொடுக்கும்" },
      { time: 28, text: "உழைப்பு" },
      { time: 29, text: "குருவிகளுக்குத் தஞ்சம் கொடுக்கும்" },
      { time: 32, text: "அரவணைப்பு" },
      { time: 33, text: "முறிந்து விழுந்தாலும் விறகாகும்" },
      { time: 36, text: "புகழ்" },
      { time: 38.5, text: "கனியைக் கொடுத்துதவும்" },
      { time: 39.5, text: "அற்புதம்" },
      { time: 41, text: "தன்னை அழிக்க வருபவனுக்கும் உயிர்" },
      { time: 44, text: "கொடுக்கும் வள்ளல்" },
      { time: 45, text: "நினைத்துப் பார்த்தால்" },
      { time: 46.5, text: "மரமே கடவுள் என்ற எண்ணம்." },
      { time: 50, text: "கெட்டதை உள் வாங்கி நல்லதை வெளிவிடும் அறிவு" },
      { time: 54, text: "கண்ணுக்குத் தெரியாத காற்றை" },
      { time: 56, text: "உணர வைக்கும் அழகு" },
      { time: 58.5, text: "இத்தனை அற்புதங்களைக் கொண்ட மரத்தை" },
      { time: 61, text: "அஃறிணையாகக் கருதாமல் உயர்திணையாக" },
      { time: 64, text: "மதிப்போம்." },
    ],
    videoPath: require("../assets/video/song2.mp4"),
  },
  {
    id: "9",
    categories: "வேகம், தொனி, உச்சரிப்பு, நயம்",
    name: "anaithum_1",
    title: "வாழ்த்து காட்டுவோம்",
    author: "கோவி,மனிதாசன்",
    image: require("../assets/kavithai9.png"),
    lyrics: [
      {
        time: 6.3,
        text: "<red>தொ</red><orange>ழி</orange><orange>ல்</orange> <red>ப</red><orange>ல</orange><red>வாய்ப்</red> <red>பெ</red><blue>ரு</blue><red>கிவ</red><blue>ரு</blue><red>ம்</red> /",
        color: "red",
        direction: "down",
      },
      {
        time: 8.6,
        text: " <red>இ</red><green>ந்</green><red>த</red> <green>நா</green><orange>ளிலே</orange> /",
        color: "red",
        direction: "down",
      },
      {
        time: 10.5,
        text: "- <green>நா</green><lightgreen>ம்</lightgreen> /",
        color: "green",
        direction: "up",
      },
      {
        time: 11.6,
        text: "<lightgreen>தொடங்கிவிட்டா</lightgreen><orange>ல்</orange> <lightgreen>உய</lightgreen><blue>ர்</blue><lightgreen>வுவ</lightgreen><blue>ரு</blue><lightgreen>ம்</lightgreen> / ",
        color: "green",
        direction: "up",
      },
      {
        time: 14.4,
        text: "<green>ந</green><lightgreen>மது</lightgreen> <lightgreen>வா</lightgreen><orange>ழ்</orange><lightgreen>வி</lightgreen><orange>லே</orange> /",
        color: "green",
        direction: "up",
      },
      {
        time: 16.5,
        text: "<red>வி</red><orange>ழி</orange><red>தி</red><blue>ற</blue><green>ந்</green><red>து</red> <red>வெ</red><orange>ளி</orange><red>யி</red><orange>ல்</orange><red>வ</red><green>ந்</green><red>து</red> / ",
        color: "red",
        direction: "down",
      },
      {
        time: 18.2,
        text: "<red>விடிய</red><orange>ல்</orange> <red>கா</red><green>ண</green><red>டா</red> / ",
        color: "red",
        direction: "down",
      },
      {
        time: 20.5,
        text: "- <lightgreen>தம்பி</lightgreen> /",
        color: "green",
        direction: "up",
      },
      {
        time: 21.6,
        text: "<lightgreen>வே</lightgreen><blue>று</blue><lightgreen>பட்டுப்</lightgreen> <lightgreen>பி</lightgreen><blue>ரி</blue><green>ந்</green><lightgreen>து</lightgreen><green>நின்</green><blue>றா</blue><orange>ல்</orange> / ",
        color: "green",
        direction: "up",
      },
      {
        time: 24,
        text: "<lightgreen>எ</lightgreen><orange>ல்லா</orange><lightgreen>ம்</lightgreen> <lightgreen>வீ</lightgreen><green>ண</green><lightgreen>டா!</lightgreen> /",
        color: "green",
        direction: "up",
      },
      {
        time: 26.5,
        text: "<red>காடுவெட்டி</red>    <red>நி</red><orange>ல</orange><green>ந்</green><red>தி</red><blue>ரு</blue><red>த்திக்</red>/ ",
        color: "red",
        direction: "down",
      },
      {
        time: 28.3,
        text: "<red>க</red><green>ண்</green><red>ட</red> <red>பெ</red><blue>ரு</blue><red>மையை</red> /",
        color: "red",
        direction: "down",
      },
      {
        time: 30.6,
        text: "- <green>நீ</green> / <lightgreen>கா</lightgreen><orange>ல</orange><lightgreen>மெ</lightgreen><orange>ல்லா</orange><lightgreen>ம்</lightgreen> <lightgreen>பேசிப்பேசி</lightgreen> / ",
        color: "green",
        direction: "up",
      },
      {
        time: 34.2,
        text: "<lightgreen>யாது</lightgreen> <lightgreen>க</lightgreen><green>ண்</green><lightgreen>ட</lightgreen><green>னை?</green> /",
        color: "green",
        direction: "up",
      },
      {
        time: 36.3,
        text: "<green>நா</green><red>டுசெ</red><orange>ல்லு</orange><red>ம்</red>    <red>புதுவ</red><orange>ழி</orange><red>யி</red><orange>ல்</orange> /",
        color: "red",
        direction: "down",
      },
      {
        time: 38.7,
        text: "<green>ந</green><red>ட</red><green>ந்</green><red>து</red> <red>பா</red><blue>ர</blue><red>டா</red> /",
        color: "red",
        direction: "down",
      },
      {
        time: 40.7,
        text: " - <lightgreen>தம்பி</lightgreen> /",
        color: "green",
        direction: "up",
      },
      {
        time: 41.8,
        text: "<green>நா</green><orange>ளை</orange><lightgreen>யு</lightgreen><green>ன்</green><blue>ற</blue><lightgreen>ன்</lightgreen> <lightgreen>கையி</lightgreen><orange>லெ</orange><green>ன்</green><blue>றே</blue> / ",
        color: "green",
        direction: "up",
      },
      {
        time: 44.1,
        text: "<lightgreen>உ</lightgreen><blue>று</blue><lightgreen>தி</lightgreen> <lightgreen>பூ</lightgreen><green>ண</green><lightgreen>டா</lightgreen>!",
        color: "green",
        direction: "up",
      },

      {
        time: 46.6,
        text: "<red>மூ</red><green>ன்</green><blue>றி</blue><green>ன</green><red>ங்கள்</red> <red>வாழ்</red><green>ந்</green><red>தபோதும்</red> / ",
        color: "red",
        direction: "down",
      },
      {
        time: 49.25,
        text: "<red>ஆட்சி ஒன்</red><blue>று</blue><red>தான்</red> / ",
        color: "red",
        direction: "down",
      },
      {
        time: 51.2,
        text: "- <lightgreen>இங்கு</lightgreen> /",
        color: "green",
        direction: "up",
      },
      {
        time: 52.4,
        text: "<lightgreen>மு</lightgreen><green>ன்னு</green><lightgreen>ய</lightgreen><blue>ரு</blue><lightgreen>ம்</lightgreen> <lightgreen>வ</lightgreen><orange>ழி</orange><lightgreen>யெவ</lightgreen><blue>ர்</blue><lightgreen>க்கும்</lightgreen> / ",
        color: "green",
        direction: "up",
      },
      {
        time: 54.5,
        text: "<lightgreen>பொதுவி</lightgreen><orange>ல்</orange> <lightgreen>ஒ</lightgreen><green>ன்</green><blue>று</blue><lightgreen>தா</lightgreen><green>ன்</green> /",
        color: "green",
        direction: "up",
      },

      {
        time: 56.2,
        text: "<red>சா</red><green>ன்</green><blue>றெ</blue><green>ன</green><red>வே</red> / ",
        color: "red",
        direction: "down",
      },
      {
        time: 57.6,
        text: "<red>ம</red><blue>ற்ற</blue><red>வி</red><green>ன</green><red>ம்</red> <red>வ</red><orange>ள</orange><red>ம்</red> <red>பெ</red><blue>ரு</blue><red>க்குது</red> /",
        color: "red",
        direction: "down",
      },
      {
        time: 60.6,
        text: "<red>சா</red><green>ன்</green><blue>றெ</blue><green>ன</green><red>வே</red> / ",
        color: "red",
        direction: "down",
      },
      {
        time: 62.1,
        text: "<red>ம</red><blue>ற்ற</blue><red>வி</red><green>ன</green><red>ம்</red> <red>வ</red><orange>ள</orange><red>ம்</red> <red>பெ</red><blue>ரு</blue><red>க்குது</red> /",
        color: "red",
        direction: "down",
      },
      {
        time: 65.2,
        text: " - <lightgreen>தம்பி</lightgreen> /",
        color: "green",
        direction: "up",
      },
      {
        time: 66.3,
        text: "<lightgreen>சா</lightgreen><green>ணு</green><lightgreen>ய</lightgreen><blue>ர்</blue><lightgreen>ந்தா</lightgreen><orange>ல்</orange>    <green>ந</green><lightgreen>ம்மி</lightgreen><green>ன</green><lightgreen>ம்</lightgreen> / ",
        color: "green",
        direction: "up",
      },
      {
        time: 67.7,
        text: "<lightgreen>ஏ</lightgreen><green>ன்</green> <lightgreen>மு</lightgreen><orange>ழ</orange><lightgreen>ம்</lightgreen> <lightgreen>ச</lightgreen><blue>று</blue><lightgreen>க்குது?</lightgreen>",
        color: "green",
        direction: "up",
      },
      {
        time: 70.5,
        text: " - <lightgreen>தம்பி</lightgreen> /",
        color: "green",
        direction: "up",
      },
      {
        time: 71.7,
        text: "<lightgreen>சா</lightgreen><green>ணு</green><lightgreen>ய</lightgreen><blue>ர்</blue><lightgreen>ந்தா</lightgreen><orange>ல்</orange>    <green>ந</green><lightgreen>ம்மி</lightgreen><green>ன</green><lightgreen>ம்</lightgreen> / ",
        color: "green",
        direction: "up",
      },
      {
        time: 74,
        text: "<lightgreen>ஏ</lightgreen><green>ன்</green> <lightgreen>மு</lightgreen><orange>ழ</orange><lightgreen>ம்</lightgreen> <lightgreen>ச</lightgreen><blue>று</blue><lightgreen>க்குது?</lightgreen>",
        color: "green",
        direction: "up",
      },
      {
        time: 77,
        text: "<red>பகுத்த</red><blue>றி</blue><red>வு</red> <red>வ</red><orange>ள</orange><blue>ர்</blue><red>ச்சியி</red><orange>ல்</orange> / ",
        color: "red",
        direction: "down",
      },
      {
        time: 78.5,
        text: "<lightgreen>நாம்</lightgreen> <lightgreen>ப</lightgreen><orange>ழை</orange><lightgreen>யவ</lightgreen><blue>ர்</blue> <lightgreen>தா</lightgreen><green>னே</green> /",
        color: "green",
        direction: "up",
      },
      {
        time: 80.5,
        text: " - <red>உயர்</red> /",
        color: "red",
        direction: "down",
      },
      {
        time: 81.2,
        text: "<red>ப</red><green>ண்</green><red>பாடு</red> <green>நெ</green><blue>றி</blue><red>யி</red><orange>லெல்லா</orange><red>ம்</red> / ",
        color: "red",
        direction: "down",
      },
      {
        time: 83.2,
        text: "<lightgreen>சி</lightgreen><blue>ற</blue><green>ந்</green><lightgreen>தவ</lightgreen><blue>ர்</blue> <lightgreen>தா</lightgreen><green>னே</green> /",
        color: "green",
        direction: "up",
      },
      {
        time: 85.3,
        text: "<red>வகுத்துவைத்து</red> <red>கு</red><blue>ற</blue><orange>ள்</orange><green>நெ</green><blue>றி</blue><red>யை</red>/  ",
        color: "red",
        direction: "down",
      },
      {
        time: 87.5,
        text: "<red>ம</red><blue>ற</blue><green>ந்</green><red>தத</red> <green>னா</green><orange>லே</orange> /",
        color: "red",
        direction: "down",
      },
      {
        time: 89.5,
        text: "- <lightgreen>தம்பி</lightgreen> /",
        color: "green",
        direction: "up",
      },
      {
        time: 90.5,
        text: "<lightgreen>வா</lightgreen><orange>ழ்</orange><green>ந்</green><lightgreen>து</lightgreen> <lightgreen>கெட்டோம்</lightgreen> /",
        color: "green",
        direction: "up",
      },
      {
        time: 92,
        text: " <lightgreen>ம</lightgreen><blue>று</blue><lightgreen>படிவா</lightgreen>/ ",
        color: "green",
        direction: "up",
      },
      {
        time: 93.3,
        text: "<lightgreen>வா</lightgreen><orange>ழ்</orange><green>ந்</green><lightgreen>து</lightgreen> <lightgreen>காட்டுவோம்!</lightgreen>",
        color: "green",
        direction: "up",
      },
      {
        time: 94.7,
        text: "- <lightgreen>தம்பி</lightgreen> /",
        color: "green",
        direction: "up",
      },
      {
        time: 96,
        text: "<lightgreen>வா</lightgreen><orange>ழ்</orange><green>ந்</green><lightgreen>து</lightgreen> <lightgreen>கெட்டோம்</lightgreen> /",
        color: "green",
        direction: "up",
      },
      {
        time: 97,
        text: " <lightgreen>ம</lightgreen><blue>று</blue><lightgreen>படிவா</lightgreen>/ ",
        color: "green",
        direction: "up",
      },
      {
        time: 98.3,
        text: "<lightgreen>வா</lightgreen><orange>ழ்</orange><green>ந்</green><lightgreen>து</lightgreen> <lightgreen>காட்டுவோம்!</lightgreen>",
        color: "green",
        direction: "up",
      },
      {
        time: 99.8,
        text: "<lightgreen>வா</lightgreen><orange>ழ்</orange><green>ந்</green><lightgreen>து</lightgreen> <lightgreen>காட்டுவோம்!</lightgreen>",
        color: "green",
        direction: "up",
      },
    ],
    videoPath: require("../assets/video/song1.mp4"),
  },
  {
    id: "10",
    categories: "வேகம், தொனி, உச்சரிப்பு, நயம்",
    name: "anaithum_2",

    title: "ஆட்டம் எதுவரை?",
    author: "செ.சீனி நைனா முகம்மது",
    image: require("../assets/kavithai10.jpg"),

    lyrics: [
      {
        time: 2.1,
        text: "<red>கைதெ</red><blue>ரி</blue> <red>யாம</red><orange>ல்</orange>/",
        color: "red",
        direction: "down",
      },
      {
        time: 4,
        text: " <red>படைத்தவ</red><green>ன்</green> <red>ஆடும்</red>/",
        color: "red",
        direction: "down",
      },
      {
        time: 5,
        text: "<lightgreen>கா</lightgreen><orange>ல</orange><lightgreen>ப்</lightgreen> <lightgreen>ப</lightgreen><green>ந்</green><lightgreen>துதா</lightgreen><green>ன்</green>/ ",
        color: "green",
        direction: "up",
      },
      {
        time: 7,
        text: "<lightgreen>உ</lightgreen><orange>ல</orange><lightgreen>கம்</lightgreen>",
        color: "green",
        direction: "up",
      },
      {
        time: 8.6,
        text: " - <red>அதி</red><orange>ல்</orange>/",
        color: "red",
        direction: "down",
      },
      {
        time: 9.5,
        text: "<red>கா</red><blue>ற்று</blue><red>ப்</red> <red>போகவே</red>/ ",
        color: "red",
        direction: "down",
      },
      {
        time: 11.3,
        text: "<red>ஓட்டை</red> <red>செய்திடும்</red>/",
        color: "red",
        direction: "down",
      },

      {
        time: 13.6,
        text: "<lightgreen>கயமை</lightgreen> <lightgreen>மனித</lightgreen><green>னா</green><orange>ல்</orange>    <lightgreen>க</lightgreen><orange>ல</orange><lightgreen>கம்</lightgreen>!",
        color: "green",
        direction: "up",
      },
      {
        time: 16.7,
        text: "<red>மெய்பு</red><blue>ரி</blue> <red>யாம</red><orange>ல்</orange>/ ",
        color: "red",
        direction: "down",
      },
      {
        time: 18.6,
        text: "<red>மேதை</red> <red>நி</red><green>னை</green><red>ப்பி</red><orange>லே</orange>/",
        color: "red",
        direction: "down",
      },
      {
        time: 20,
        text: "<lightgreen>மிகைக்கத்</lightgreen> <lightgreen>துடிக்கி</lightgreen><blue>றா</blue><green>ன்</green> <lightgreen>எதையும்</lightgreen> ",
        color: "green",
        direction: "up",
      },
      {
        time: 23.2,
        text: "- <red>இவ</red><green>ன்</green>/",
        color: "red",
        direction: "down",
      },
      {
        time: 24,
        text: "<red>வீட்டைக்</red> <red>கொ</red><orange>ளு</orange><red>த்தியே</red>/ ",
        color: "red",
        direction: "down",
      },
      {
        time: 25.5,
        text: "<red>வெ</red><orange>ளி</orange><red>ச்சம்</red> <red>தேடினா</red><orange>ல்</orange>/",
        color: "red",
        direction: "down",
      },
      {
        time: 27,
        text: "<lightgreen>வெ</lightgreen><blue>ற்றி</blue> <lightgreen>சாம்பலாய்</lightgreen><orange>லா</orange><lightgreen>ய்</lightgreen> ",
        color: "green",
        direction: "up",
      },
      {
        time: 28,
        text: "<lightgreen>முடியும்</lightgreen>!",
        color: "green",
        direction: "up",
      },
      {
        time: 30,
        text: "<red>ம</red><green>ண்ணை</green><red>த்</red> <red>து</red><orange>ளை</orange><red>க்கி</red><blue>றா</blue><green>ன்</green>/",
        color: "red",
        direction: "down",
      },
      {
        time: 32,
        text: " <red>பொ</red><green>ன்னை</green><red>ப்</red> <red>பி</red><blue>ரி</blue><red>க்கி</red><blue>றா</blue><green>ன்</green>/",
        color: "red",
        direction: "down",
      },
      {
        time: 33.6,
        text: "<red>எ</red><green>ண்ணெ</green><red>ய்</red> <red>எடுக்கி</red><blue>றா</blue><green>ன்</green>/ ",
        color: "red",
        direction: "down",
      },
      {
        time: 34.9,
        text: "<lightgreen>ச</lightgreen><blue>ரி</blue><lightgreen>தா</lightgreen><green>ன்</green> - <lightgreen>ஏ</lightgreen><green>ன்</green>/",
        color: "green",
        direction: "up",
      },
      {
        time: 37,
        text: "<red>ம</red><orange>லை</orange><red>யைத்</red> <red>தக</red><blue>ர்</blue><red>க்கி</red><blue>றா</blue><green>ன்</green>/ ",
        color: "red",
        direction: "down",
      },
      {
        time: 38.3,
        text: "<red>கட</red><orange>லை</orange><red>த்</red> <red>தூ</red><blue>ர்</blue><red>க்கி</red><blue>றா</blue><green>ன்?</green>/",
        color: "red",
        direction: "down",
      },
      {
        time: 40.4,
        text: "<lightgreen>வ</lightgreen><blue>ர</blue><lightgreen>ம்பு</lightgreen> <lightgreen>மீ</lightgreen><blue>றி</blue><lightgreen>டும் </lightgreen> <lightgreen>வெ</lightgreen><blue>றி</blue><lightgreen>தா</lightgreen><green>ன்</green>!",
        color: "green",
        direction: "up",
      },
      {
        time: 43.3,
        text: "<red>ம</red><green>ண்ணை</green><red>க் </red> <red>கெடுத்தவ</red><green>ன்</green>/ ",
        color: "red",
        direction: "down",
      },
      {
        time: 45,
        text: "<red>வி</red><green>ண்ணை</green><red>க்</red> <red>கெடுக்கவும்</red>/",
        color: "red",
        direction: "down",
      },
      {
        time: 46.6,
        text: "<lightgreen>எ</lightgreen><green>ண்ணி</green>  <lightgreen> வைக்கி</lightgreen><blue>றா</blue><green>ன்</green> ",
        color: "green",
        direction: "up",
      },
      {
        time: 48,
        text: "<lightgreen>கு</lightgreen><blue>றி</blue><lightgreen>தா</lightgreen><green>ன்</green> ",
        color: "green",
        direction: "up",
      },
      {
        time: 49,
        text: "<red>இவ</red><green>ன்</green>/",
        color: "red",
        direction: "down",
      },
      {
        time: 50,
        text: "<red>ம</red><green>ன</green><red>த்தைக்</red> <red>கெடுப்பதும்</red>/ ",
        color: "red",
        direction: "down",
      },
      {
        time: 51,
        text: "<red>கு</red><green>ண</green><red>த்தை</red> <red>அ</red><orange>ழி</orange><red>ப்பதும்</red>/",
        color: "red",
        direction: "down",
      },
      {
        time: 52.5,
        text: "<lightgreen>த</lightgreen><green>ன</green><lightgreen>க்குத்</lightgreen> <lightgreen>த</lightgreen><lightgreen>ன</lightgreen><lightgreen>க்கெ</lightgreen><green>ன்னு</green><lightgreen>ம்</lightgreen> ",
        color: "green",
        direction: "up",
      },
      {
        time: 54.3,
        text: "<lightgreen>வெ</lightgreen><blue>றி</blue><lightgreen>தா</lightgreen><green>ன்!</green>/ ",
        color: "green",
        direction: "up",
      },
      {
        time: 55.3,
        text: "<red>கா</red><blue>ற்றி</blue><orange>ல்</orange> <red>நஞ்சையும்</red>/ ",
        color: "red",
        direction: "down",
      },
      {
        time: 57,
        text: "<red>கட</red><orange>லில்</orange> <red>க</red><orange>ழி</orange><red>வையும்</red>/",
        color: "red",
        direction: "down",
      },
      {
        time: 59,
        text: " <lightgreen>க</lightgreen><green>ண</green><lightgreen>க்கு</lightgreen> <lightgreen>வ</lightgreen><orange>ழ</orange><lightgreen>க்கி</lightgreen><green>ன்</green><blue>றி</blue>  ",
        color: "green",
        direction: "up",
      },
      {
        time: 60,
        text: "<lightgreen>நி</lightgreen><blue>றை</blue><lightgreen>த்தா</lightgreen><green>ன்</green>",
        color: "green",
        direction: "up",
      },
      {
        time: 61.7,
        text: "- <red>அட</red><blue>ர்</blue> <red>காட்டை</red> <red>அ</red><orange>ழி</orange><red>த்ததி</red><orange>ல்</orange>/ ",
        color: "red",
        direction: "down",
      },
      {
        time: 63.8,
        text: "<red>கா</red><green>ணு</green><red>ம் </red><red>வி</red><orange>ல</orange><red>ங்கெ</red><orange>லா</orange><red>ம்</red>/",
        color: "red",
        direction: "down",
      },
      {
        time: 65,
        text: "<lightgreen>வேட்டை யாடியே</lightgreen> <lightgreen>ஒ</lightgreen><orange>ழி</orange><lightgreen>த்தா</lightgreen><green>ன்!</green>/",
        color: "green",
        direction: "up",
      },
      {
        time: 68,
        text: "<red>ஆ</red><blue>ற்றை</blue><red>ச்</red> <red>சாக்கடை</red> <red>ஆக்கி</red> / ",
        color: "red",
        direction: "down",
      },
      {
        time: 70,
        text: "<lightgreen>உயி</lightgreen><blue>ர்</blue><lightgreen>க</lightgreen><orange>ளை</orange> <lightgreen>அ</lightgreen><orange>ழி</orange><lightgreen>க்கும் </lightgreen> /",
        color: "green",
        direction: "up",
      },
      {
        time: 72,
        text: "<green>நோ</green><lightgreen>ய்க</lightgreen><orange>ளை</orange> <lightgreen>வ</lightgreen><orange>ள</orange><blue>ர்</blue><lightgreen>த்தான்</lightgreen> <green>தன்</green>/",
        color: "green",
        direction: "up",
      },
      {
        time: 74.1,
        text: "<lightgreen>அ</lightgreen><blue>றி</blue><lightgreen>வை</lightgreen> <lightgreen>நம்பியே,</lightgreen> ",
        color: "green",
        direction: "up",
      },
      {
        time: 75.7,
        text: "<lightgreen>இ</lightgreen><blue>றை</blue><lightgreen>வ</lightgreen><green>ன்</green> <lightgreen>வ</lightgreen><orange>ழ</orange><lightgreen>ங்கிடும்</lightgreen> ",
        color: "green",
        direction: "up",
      },
      {
        time: 77,
        text: "<lightgreen>அ</lightgreen><blue>ரு</blue><orange>ளி</orange><green>ன்</green> <lightgreen>போ</lightgreen><blue>ர்</blue><lightgreen>வையைக்</lightgreen>/ ",
        color: "green",
        direction: "up",
      },
      {
        time: 78,
        text: "<lightgreen>கி</lightgreen><orange>ழி</orange><lightgreen>த்தா</lightgreen><green>ன்</green>!/",
        color: "green",
        direction: "up",
      },
      {
        time: 80,
        text: "<red>உ</red><green>ண</green><red>வி</red><green>ன்</green> <red>சுவையி</red><orange>லே</orange>/",
        color: "red",
        direction: "down",
      },
      {
        time: 81.5,
        text: " <red>உ</red><blue>ரு</blue><red>வி</red><green>ன்</green> <red>அ</red><orange>ழ</orange><red>கி</red><orange>லே</orange>/",
        color: "red",
        direction: "down",
      },
      {
        time: 83,
        text: "<lightgreen>உட</lightgreen><orange>லில்</orange> <lightgreen>செய</lightgreen><blue>ற்</blue><lightgreen>கையைத்</lightgreen> ",
        color: "green",
        direction: "up",
      },
      {
        time: 84.5,
        text: "<lightgreen>தி</lightgreen><green>ணி</green><lightgreen>த்தா</lightgreen><green>ன்</green> ",
        color: "green",
        direction: "up",
      },
      {
        time: 86,
        text: "- <red>த</red><green>ன்</green>/ <red>உ</red><blue>ரி</blue><red>மை</red> <red>மீ</red><blue>றி</blue><red>யே</red>/ ",
        color: "red",
        direction: "down",
      },
      {
        time: 88,
        text: "<red>ஒ</red><orange>ழு</orange><red>ங்கும்</red> <red>மா</red><blue>றி</blue><red>யே</red>/",
        color: "red",
        direction: "down",
      },
      {
        time: 89.4,
        text: "<lightgreen>உயி</lightgreen><blue>ரி</blue><green>ன்</green> <lightgreen>இய</lightgreen><blue>ற்</blue><lightgreen>கையைக்</lightgreen> ",
        color: "green",
        direction: "up",
      },
      {
        time: 91,
        text: "<lightgreen>கெடுத்தா</lightgreen><green>ன்</green>!",
        color: "green",
        direction: "up",
      },
      {
        time: 92,
        text: "<red>அ</red><green>ணு</green><red>வி</red><green>ன்</green> <red>ஆ</red><blue>ற்ற</blue><orange>லால்</orange>/ ",
        color: "red",
        direction: "down",
      },
      {
        time: 94,
        text: "<red>அவ</red><green>னி</green> <red>மு</red><orange>ழு</orange><lightgreen>வதும்</lightgreen>!",
        color: "red",
        direction: "down",
      },
      {
        time: 96,
        text: "<lightgreen>அடக்கி  </lightgreen> <lightgreen>ஆ</lightgreen><orange>ள</orange><lightgreen>வே</lightgreen> <lightgreen>துடித்தா</lightgreen><green>ன்</green>!",
        color: "green",
        direction: "up",
      },
      {
        time: 98.7,
        text: "<lightgreen>இவன்</lightgreen> <lightgreen>ஆட்டம்</lightgreen> <lightgreen>எதுவ</lightgreen><blue>ரை</blue>?/",
        color: "green",
        direction: "up",
      },
      {
        time: 101,
        text: "<red>ஆ</red><orange>ழி</orange><red>ப்</red> <red>பே</red><blue>ர</blue><orange>லை</orange>!",
        color: "red",
        direction: "down",
      },
      {
        time: 102.2,
        text: "<lightgreen>அ</lightgreen><orange>ழி</orange><lightgreen>க்கும் </lightgreen><lightgreen>வ</lightgreen><blue>ரை</blue><lightgreen>தா</lightgreen><green>னே</green> <lightgreen>குதிப்பா</lightgreen><green>ன்</green>!",
        color: "green",
        direction: "up",
      },
    ],
    videoPath: require("../assets/video/song3.mp4"),
  },
];
